language: scala
branches:
  only:
    - master
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
script:
  - 'sbt "clean" "coverage" "+ testOnly * -- -l com.lynbrookrobotics.potassium.PerfTest" "coverageReport"'
  - 'sbt coverageAggregate'
jdk: oraclejdk8
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ./deploy.sh; fi'
