sudo: required
language: scala
branches:
  only:
    - master
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
  - rvm use 2.3.3 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll
script:
  - mkdir -p ~/.sbt/0.13/plugins
  - echo 'addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC5")' > ~/.sbt/0.13/plugins/build.sbt
  - 'sbt "clean" "coverage" "test" "coverageReport"'
  - 'sbt coverageAggregate'
jdk: oraclejdk8
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ./deploy.sh; fi'
cache:
   directories:
   - $HOME/.coursier
